CREATE DATABASE BESAFE_APPLICATION;
USE  BESAFE_APPLICATION;
CREATE TABLE AUTH(
    EMAIL VARCHAR(100) PRIMARY KEY,
    PASSWORD TEXT NOT NULL
);

CREATE TABLE USER (
    ID VARCHAR(36) PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PHONE VARCHAR(10) NOT NULL,
    DOB DATE NOT NULL,
    ABOUT TEXT 
);

CREATE TABLE CONTACTS(
    HOST_ID VARCHAR(36) NOT NULL,
    CONTACT_ID VARCHAR(36) NOT NULL,
  ALLOW_ACCESS BOOLEAN NOT NULL DEFAULT TRUE,
    FOREIGN KEY (HOST_ID) REFERENCES USER(ID),
    FOREIGN KEY (CONTACT_ID) REFERENCES USER(ID)
);

CREATE TABLE MEDICAL_RECORD (
    USER_ID VARCHAR(36) PRIMARY KEY,
    BLOOD_GROUP VARCHAR(5) NOT NULL,
    BIRTH_MARK TEXT NOT NULL
);

