CREATE DATABASE SHEGUARD_APPLICATION_DATABASE;

USE SHEGUARD_APPLICATION_DATABASE;

CREATE TABLE AUTH(
    EMAIL VARCHAR(100) PRIMARY KEY,
    PASSWORD TEXT NOT NULL
);

CREATE TABLE USER (
    EMAIL VARCHAR(100) PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    PHONE VARCHAR(10) NOT NULL,
    DOB DATE NOT NULL,
    ABOUT TEXT 
);

CREATE TABLE CONTACTS(
    HOST_EMAIL VARCHAR(36) NOT NULL,
    CONTACT_EMAIL VARCHAR(36) NOT NULL,
    UNIQUE(HOST_EMAIL,CONTACT_EMAIL),
    FOREIGN KEY (HOST_EMAIL) REFERENCES USER(EMAIL),
    FOREIGN KEY (CONTACT_EMAIL) REFERENCES USER(EMAIL)
);

CREATE TABLE MEDICAL_RECORD (
    USER_EMAIL VARCHAR(100) PRIMARY KEY,
    BLOOD_GROUP VARCHAR(5) NOT NULL,
    BIRTH_MARK TEXT NOT NULL,
    FOREIGN KEY (USER_EMAIL) REFERENCES USER(EMAIL)
);

CREATE VIEW USER_PROFILE AS
  SELECT U.*,M.BLOOD_GROUP AS 'BLOOD GROUP',M.BIRTH_MARK AS 'BIRTH MARK'
  FROM USER U
  INNER JOIN MEDICAL_RECORD M ON U.EMAIL=M.USER_EMAIL;

CREATE VIEW CONTACT_LIST AS SELECT U.NAME AS 'CONTACT_NAME',U.PHONE AS 'CONTACT_PHONE',U.EMAIL AS 'CONTACT_EMAIL'
,C.HOST_EMAIL AS '' FROM USER U INNER JOIN CONTACTS C ON C.CONTACT_EMAIL = U.EMAIL;



